name: test_package
description: Testing how to let flutter apps use files from a dart package.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

flutter:
  assets:
    - lib/data/

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9

  mocktail: ^1.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
